version: "3.8"

services:
  mongo:
    image: mongo:5.0
    container_name: mongo_db
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  app:
    build: .
    container_name: kivy_health_app
    volumes:
      - .:/app
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo:27017
      - PYTHONUNBUFFERED=1
    stdin_open: true
    tty: true
    ports:
      - "5000:5000"  # Optional, if your app exposes an API/UI

volumes:
  mongo_data:
